version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.1-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - 8080:80

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: quickbid
      MYSQL_USER: quickbid
      MYSQL_PASSWORD: quickbid
      MYSQL_ROOT_PASSWORD: quickbid
    ports:
      - 3307:3306

  redis:
    image: redis:latest
    ports:
    - 6380:6379
    networks:
      net: {}

  rabbitmq:
    image: rabbitmq:latest
    ports:
    - 5673:5672
    networks:
      net: {}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8081:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    depends_on:
        - mysql

networks:
  net:
    name: quickbid_net